const animals = [
  "Bear 🐻",
  "Panda 🐼",
  "Fox 🦊",
  "Tiger 🐯",
  "Wolf 🐺",
  "Koala 🐨",
  "Cat 🐱",
  "Rabbit 🐰",
  "Penguin 🐧",
  "Owl 🦉",
  "Deer 🦌",
  "Otter 🦦",
  "Raccoon 🦝",
  "Squirrel 🐿️",
  "Seal 🦭",
  "Dolphin 🐬",
  "Whale 🐋",
  "Shark 🦈",
  "Octopus 🐙",
  "Turtle 🐢",
  "Butterfly 🦋",
  "Bee 🐝",
  "Ladybug 🐞",
  "Peacock 🦚",
  "Swan 🦢",
  "Parrot 🦜",
  "Falcon 🦅",
  "Raven 🐦",
  "Duck 🦆",
  "Chicken 🐔",
  "Hamster 🐹",
  "Hedgehog 🦔",
  "Frog 🐸",
  "Llama 🦙",
  "Alpaca 🦙",
  "Horse 🐴",
  "Zebra 🦓",
  "Giraffe 🦒",
  "Elephant 🐘",
  "Rhino 🦏",
  "Hippo 🦛",
  "Camel 🐪",
  "Goat 🐐",
  "Sheep 🐑",
  "Cow 🐮",
  "Bison 🦬",
  "Moose 🫎",
  "Polar Bear 🐻‍❄️",
  "Red Panda ❤️🐼",
  "Snow Leopard 🐆",
  "Panther 🐈⬛",
  "Phoenix 🔥",
  "Dragon 🐉",
  "Unicorn 🦄",
  "Griffin 🪽",
  "Moon 🌙",
  "Comet ☄️",
  "Aurora 🌌",
  "Ocean 🌊",
  "Forest 🌲",
  "Maple 🍁",
  "Lotus 🪷",
  "Sunflower 🌻",
  "Lavender 💜",
  "Coffee ☕",
  "Cookie 🍪",
  "Donut 🍩",
  "Pizza 🍕",
  "Noodles 🍜",
  "Potato 🥔",
  "Pickle 🥒",
  "Shadow 🌑",
  "Phantom 👻",
  "Ghost 👻",
  "Cipher 🔐",
  "Nebula ✨",
  "Eclipse 🌘",
  "Mirage 🪞",
  "Nova ⭐",
  "Meteor ☄️",
  "Galaxy 🌠",
  "Storm ⛈️",
  "Lightning ⚡",
  "Snowflake ❄️",
  "Crystal 💎",
  "Sapphire 💙",
  "Emerald 💚",
  "Ruby ❤️",
  "Pearl 🤍",
  "Velvet 🖤",
  "Mystic 🔮",
  "Harmony 🎵",
  "Echo 🎧",
  "Dream ☁️",
  "Voyager 🚀",
  "Explorer 🧭",
  "Wanderer 🌍",
  "Nomad 🏕️",
  "Guardian 🛡️",
  "Legend 👑",
];

export function generateAnonymousName() {
  const animal =
    animals[Math.floor(Math.random() * animals.length)];

  return `Anonymous ${animal}`;
}